/**
 * src/lib/corridors.js
 * 
 * Centralized Intercity Logistics Corridors & Route Registry for GoMyTruck PSEO/AEO.
 * Contains high-traffic national highway routes with distances, transit hours,
 * toll estimates, highway IDs, and backhaul return-load profiles.
 */

export const POPULAR_CORRIDORS = [
  // Delhi NCR Outbound Corridors
  {
    slug: "delhi-to-jaipur",
    originSlug: "new-delhi",
    originName: "Delhi",
    originState: "Delhi",
    destSlug: "jaipur",
    destName: "Jaipur",
    destState: "Rajasthan",
    distanceKm: 280,
    transitHours: 6,
    highway: "NH-48 (Delhi-Jaipur Expressway)",
    estimatedTolls: 420,
    popularCargo: "Industrial goods, textiles, automotive components, consumer electronics",
    returnLoadAvailable: true,
  },
  {
    slug: "jaipur-to-delhi",
    originSlug: "jaipur",
    originName: "Jaipur",
    originState: "Rajasthan",
    destSlug: "new-delhi",
    destName: "Delhi",
    destState: "Delhi",
    distanceKm: 280,
    transitHours: 6,
    highway: "NH-48 (Jaipur-Delhi Expressway)",
    estimatedTolls: 420,
    popularCargo: "Handicrafts, marble & tiles, garments, agricultural produce",
    returnLoadAvailable: true,
  },
  {
    slug: "delhi-to-lucknow",
    originSlug: "new-delhi",
    originName: "Delhi",
    originState: "Delhi",
    destSlug: "lucknow",
    destName: "Lucknow",
    destState: "Uttar Pradesh",
    distanceKm: 535,
    transitHours: 8,
    highway: "Yamuna & Agra-Lucknow Expressway",
    estimatedTolls: 890,
    popularCargo: "FMCG, hardware, consumer retail, packaged food",
    returnLoadAvailable: true,
  },
  {
    slug: "lucknow-to-delhi",
    originSlug: "lucknow",
    originName: "Lucknow",
    originState: "Uttar Pradesh",
    destSlug: "new-delhi",
    destName: "Delhi",
    destState: "Delhi",
    distanceKm: 535,
    transitHours: 8,
    highway: "Agra-Lucknow & Yamuna Expressway",
    estimatedTolls: 890,
    popularCargo: "Chikan textile, seasonal mangoes, brassware, leather products",
    returnLoadAvailable: true,
  },
  {
    slug: "delhi-to-chandigarh",
    originSlug: "new-delhi",
    originName: "Delhi",
    originState: "Delhi",
    destSlug: "chandigarh",
    destName: "Chandigarh",
    destState: "Punjab",
    distanceKm: 245,
    transitHours: 5,
    highway: "NH-44 (Grand Trunk Road)",
    estimatedTolls: 380,
    popularCargo: "Pharmaceuticals, retail goods, electronics, MSME spare parts",
    returnLoadAvailable: true,
  },
  {
    slug: "chandigarh-to-delhi",
    originSlug: "chandigarh",
    originName: "Chandigarh",
    originState: "Punjab",
    destSlug: "new-delhi",
    destName: "Delhi",
    destState: "Delhi",
    distanceKm: 245,
    transitHours: 5,
    highway: "NH-44 (Grand Trunk Road)",
    estimatedTolls: 380,
    popularCargo: "Industrial machinery, pharmaceutical APIs, tractor spares",
    returnLoadAvailable: true,
  },
  {
    slug: "delhi-to-ludhiana",
    originSlug: "new-delhi",
    originName: "Delhi",
    originState: "Delhi",
    destSlug: "ludhiana",
    destName: "Ludhiana",
    destState: "Punjab",
    distanceKm: 315,
    transitHours: 6,
    highway: "NH-44",
    estimatedTolls: 490,
    popularCargo: "Raw yarn, machinery parts, consumer goods, e-commerce",
    returnLoadAvailable: true,
  },
  {
    slug: "ludhiana-to-delhi",
    originSlug: "ludhiana",
    originName: "Ludhiana",
    originState: "Punjab",
    destSlug: "new-delhi",
    destName: "Delhi",
    destState: "Delhi",
    distanceKm: 315,
    transitHours: 6,
    highway: "NH-44",
    estimatedTolls: 490,
    popularCargo: "Bicycle parts, woolen garments, fasteners, light engineering tools",
    returnLoadAvailable: true,
  },

  // Mumbai & Maharashtra Corridors
  {
    slug: "mumbai-to-pune",
    originSlug: "mumbai",
    originName: "Mumbai",
    originState: "Maharashtra",
    destSlug: "pune",
    destName: "Pune",
    destState: "Maharashtra",
    distanceKm: 150,
    transitHours: 3.5,
    highway: "Mumbai-Pune Expressway (NH-48)",
    estimatedTolls: 320,
    popularCargo: "Automotive components, IT hardware, pharmaceuticals, retail FMCG",
    returnLoadAvailable: true,
  },
  {
    slug: "pune-to-mumbai",
    originSlug: "pune",
    originName: "Pune",
    originState: "Maharashtra",
    destSlug: "mumbai",
    destName: "Mumbai",
    destState: "Maharashtra",
    distanceKm: 150,
    transitHours: 3.5,
    highway: "Mumbai-Pune Expressway (NH-48)",
    estimatedTolls: 320,
    popularCargo: "Auto ancillary, export engineering consignments, port cargo for JNPT",
    returnLoadAvailable: true,
  },
  {
    slug: "ahmedabad-to-mumbai",
    originSlug: "ahmedabad",
    originName: "Ahmedabad",
    originState: "Gujarat",
    destSlug: "mumbai",
    destName: "Mumbai",
    destState: "Maharashtra",
    distanceKm: 525,
    transitHours: 10,
    highway: "NH-48 (Western Freight Corridor)",
    estimatedTolls: 820,
    popularCargo: "Denim & textiles, chemicals, ceramic tiles, packaged food",
    returnLoadAvailable: true,
  },
  {
    slug: "mumbai-to-ahmedabad",
    originSlug: "mumbai",
    originName: "Mumbai",
    originState: "Maharashtra",
    destSlug: "ahmedabad",
    destName: "Ahmedabad",
    destState: "Gujarat",
    distanceKm: 525,
    transitHours: 10,
    highway: "NH-48 (Western Freight Corridor)",
    estimatedTolls: 820,
    popularCargo: "Import electronics, plastic raw materials, pharma chemicals, consumer durables",
    returnLoadAvailable: true,
  },
  {
    slug: "mumbai-to-nagpur",
    originSlug: "mumbai",
    originName: "Mumbai",
    originState: "Maharashtra",
    destSlug: "nagpur",
    destName: "Nagpur",
    destState: "Maharashtra",
    distanceKm: 700,
    transitHours: 12,
    highway: "Samruddhi Mahamarg Expressway",
    estimatedTolls: 1100,
    popularCargo: "Containerized port cargo, machinery, steel, consumer appliances",
    returnLoadAvailable: true,
  },
  {
    slug: "nagpur-to-mumbai",
    originSlug: "nagpur",
    originName: "Nagpur",
    originState: "Maharashtra",
    destSlug: "mumbai",
    destName: "Mumbai",
    destState: "Maharashtra",
    distanceKm: 700,
    transitHours: 12,
    highway: "Samruddhi Mahamarg Expressway",
    estimatedTolls: 1100,
    popularCargo: "Nagpur oranges & produce, coal derivatives, steel fabrications",
    returnLoadAvailable: true,
  },

  // South India Corridors
  {
    slug: "bengaluru-to-chennai",
    originSlug: "bengaluru",
    originName: "Bengaluru",
    originState: "Karnataka",
    destSlug: "chennai",
    destName: "Chennai",
    destState: "Tamil Nadu",
    distanceKm: 345,
    transitHours: 6.5,
    highway: "NH-48 / Bengaluru-Chennai Expressway",
    estimatedTolls: 520,
    popularCargo: "Electronics, automotive spares, aerospace parts, fresh milk & produce",
    returnLoadAvailable: true,
  },
  {
    slug: "chennai-to-bengaluru",
    originSlug: "chennai",
    originName: "Chennai",
    originState: "Tamil Nadu",
    destSlug: "bengaluru",
    destName: "Bengaluru",
    destState: "Karnataka",
    distanceKm: 345,
    transitHours: 6.5,
    highway: "NH-48",
    estimatedTolls: 520,
    popularCargo: "Import port cargo, leather goods, auto ancillaries, electrical hardware",
    returnLoadAvailable: true,
  },
  {
    slug: "hyderabad-to-bengaluru",
    originSlug: "hyderabad",
    originName: "Hyderabad",
    originState: "Telangana",
    destSlug: "bengaluru",
    destName: "Bengaluru",
    destState: "Karnataka",
    distanceKm: 575,
    transitHours: 9.5,
    highway: "NH-44 (North-South Corridor)",
    estimatedTolls: 940,
    popularCargo: "Pharma bulk drugs, poultry products, e-commerce, seeds & fertilizers",
    returnLoadAvailable: true,
  },
  {
    slug: "bengaluru-to-hyderabad",
    originSlug: "bengaluru",
    originName: "Bengaluru",
    originState: "Karnataka",
    destSlug: "hyderabad",
    destName: "Hyderabad",
    destState: "Telangana",
    distanceKm: 575,
    transitHours: 9.5,
    highway: "NH-44 (North-South Corridor)",
    estimatedTolls: 940,
    popularCargo: "Coffee & spices, heavy electrical components, electronics",
    returnLoadAvailable: true,
  },
  {
    slug: "chennai-to-coimbatore",
    originSlug: "chennai",
    originName: "Chennai",
    originState: "Tamil Nadu",
    destSlug: "coimbatore",
    destName: "Coimbatore",
    destState: "Tamil Nadu",
    distanceKm: 505,
    transitHours: 8.5,
    highway: "NH-544 / NH-48",
    estimatedTolls: 780,
    popularCargo: "Port containers, auto spare parts, consumer packaged goods",
    returnLoadAvailable: true,
  },
  {
    slug: "coimbatore-to-chennai",
    originSlug: "coimbatore",
    originName: "Coimbatore",
    originState: "Tamil Nadu",
    destSlug: "chennai",
    destName: "Chennai",
    destState: "Tamil Nadu",
    distanceKm: 505,
    transitHours: 8.5,
    highway: "NH-544 / NH-48",
    estimatedTolls: 780,
    popularCargo: "Textile machinery, pumps & motors, cotton hosiery, auto forgings",
    returnLoadAvailable: true,
  },

  // East & Central India Corridors
  {
    slug: "kolkata-to-patna",
    originSlug: "kolkata",
    originName: "Kolkata",
    originState: "West Bengal",
    destSlug: "patna",
    destName: "Patna",
    destState: "Bihar",
    distanceKm: 585,
    transitHours: 12,
    highway: "NH-19 / GT Road Corridor",
    estimatedTolls: 910,
    popularCargo: "Consumer durables, jute bags, footwear, hardware, wholesale electronics",
    returnLoadAvailable: true,
  },
  {
    slug: "patna-to-kolkata",
    originSlug: "patna",
    originName: "Patna",
    originState: "Bihar",
    destSlug: "kolkata",
    destName: "Kolkata",
    destState: "West Bengal",
    distanceKm: 585,
    transitHours: 12,
    highway: "NH-19 / GT Road Corridor",
    estimatedTolls: 910,
    popularCargo: "Agricultural foodgrains, pulses, makhana, return containers",
    returnLoadAvailable: true,
  },
  {
    slug: "kolkata-to-bhubaneswar",
    originSlug: "kolkata",
    originName: "Kolkata",
    originState: "West Bengal",
    destSlug: "bhubaneswar",
    destName: "Bhubaneswar",
    destState: "Odisha",
    distanceKm: 440,
    transitHours: 8,
    highway: "NH-16 (East Coast Highway)",
    estimatedTolls: 650,
    popularCargo: "FMCG, fish & seafood, textile goods, paints & chemicals",
    returnLoadAvailable: true,
  },
  {
    slug: "bhubaneswar-to-kolkata",
    originSlug: "bhubaneswar",
    originName: "Bhubaneswar",
    originState: "Odisha",
    destSlug: "kolkata",
    destName: "Kolkata",
    destState: "West Bengal",
    distanceKm: 440,
    transitHours: 8,
    highway: "NH-16 (East Coast Highway)",
    estimatedTolls: 650,
    popularCargo: "Steel sheets, minerals, ceramics, industrial refractory bricks",
    returnLoadAvailable: true,
  },
  {
    slug: "kolkata-to-ranchi",
    originSlug: "kolkata",
    originName: "Kolkata",
    originState: "West Bengal",
    destSlug: "ranchi",
    destName: "Ranchi",
    destState: "Jharkhand",
    distanceKm: 410,
    transitHours: 8.5,
    highway: "NH-19 / NH-43",
    estimatedTolls: 620,
    popularCargo: "Packaging materials, wholesale retail goods, pharmaceuticals, tyres",
    returnLoadAvailable: true,
  },
  {
    slug: "kolkata-to-siliguri",
    originSlug: "kolkata",
    originName: "Kolkata",
    originState: "West Bengal",
    destSlug: "siliguri",
    destName: "Siliguri",
    destState: "West Bengal",
    distanceKm: 570,
    transitHours: 13,
    highway: "NH-12 (North Bengal Corridor)",
    estimatedTolls: 880,
    popularCargo: "North-East transit freight, edible oil, construction materials, FMCG",
    returnLoadAvailable: true,
  },
  {
    slug: "siliguri-to-kolkata",
    originSlug: "siliguri",
    originName: "Siliguri",
    originState: "West Bengal",
    destSlug: "kolkata",
    destName: "Kolkata",
    destState: "West Bengal",
    distanceKm: 570,
    transitHours: 13,
    highway: "NH-12",
    estimatedTolls: 880,
    popularCargo: "Darjeeling & Assam tea crates, timber, ginger & cardamoms",
    returnLoadAvailable: true,
  },
  {
    slug: "kolkata-to-guwahati",
    originSlug: "kolkata",
    originName: "Kolkata",
    originState: "West Bengal",
    destSlug: "guwahati",
    destName: "Guwahati",
    destState: "Assam",
    distanceKm: 990,
    transitHours: 24,
    highway: "NH-27 (East-West Highway Corridor)",
    estimatedTolls: 1450,
    popularCargo: "Heavy machinery, pharmaceuticals, industrial chemicals, retail merchandise",
    returnLoadAvailable: true,
  },
  {
    slug: "kolkata-to-delhi",
    originSlug: "kolkata",
    originName: "Kolkata",
    originState: "West Bengal",
    destSlug: "new-delhi",
    destName: "Delhi",
    destState: "Delhi",
    distanceKm: 1490,
    transitHours: 28,
    highway: "NH-19 (Golden Quadrilateral Trunk Route)",
    estimatedTolls: 2400,
    popularCargo: "Full truck load (FTL) manufacturing freight, tea, packaging, textiles",
    returnLoadAvailable: true,
  },
  {
    slug: "delhi-to-kolkata",
    originSlug: "new-delhi",
    originName: "Delhi",
    originState: "Delhi",
    destSlug: "kolkata",
    destName: "Kolkata",
    destState: "West Bengal",
    distanceKm: 1490,
    transitHours: 28,
    highway: "NH-19 (Golden Quadrilateral Trunk Route)",
    estimatedTolls: 2400,
    popularCargo: "Automotive spares, electronics, cosmetics, hardware supplies",
    returnLoadAvailable: true,
  },

  // Central India & MP Corridors
  {
    slug: "indore-to-bhopal",
    originSlug: "indore",
    originName: "Indore",
    originState: "Madhya Pradesh",
    destSlug: "bhopal",
    destName: "Bhopal",
    destState: "Madhya Pradesh",
    distanceKm: 195,
    transitHours: 4,
    highway: "State Highway 18 / NH-46",
    estimatedTolls: 280,
    popularCargo: "Pharma medicines, soybean oil, wholesale textiles, grocery supplies",
    returnLoadAvailable: true,
  },
  {
    slug: "bhopal-to-indore",
    originSlug: "bhopal",
    originName: "Bhopal",
    originState: "Madhya Pradesh",
    destSlug: "indore",
    destName: "Indore",
    destState: "Madhya Pradesh",
    distanceKm: 195,
    transitHours: 4,
    highway: "SH-18 / NH-46",
    estimatedTolls: 280,
    popularCargo: "Heavy electricals (BHEL spares), agricultural wheat, tractor parts",
    returnLoadAvailable: true,
  },
  {
    slug: "jaipur-to-ahmedabad",
    originSlug: "jaipur",
    originName: "Jaipur",
    originState: "Rajasthan",
    destSlug: "ahmedabad",
    destName: "Ahmedabad",
    destState: "Gujarat",
    distanceKm: 660,
    transitHours: 12,
    highway: "NH-48 / Western Corridor",
    estimatedTolls: 920,
    popularCargo: "Textiles, ceramic tiles, marble, consumer goods",
    returnLoadAvailable: true,
  },
  {
    slug: "ahmedabad-to-jaipur",
    originSlug: "ahmedabad",
    originName: "Ahmedabad",
    originState: "Gujarat",
    destSlug: "jaipur",
    destName: "Jaipur",
    destState: "Rajasthan",
    distanceKm: 660,
    transitHours: 12,
    highway: "NH-48 / Western Corridor",
    estimatedTolls: 920,
    popularCargo: "Denim, industrial chemicals, plastic goods, pharmaceuticals",
    returnLoadAvailable: true,
  },
  {
    slug: "delhi-to-kanpur",
    originSlug: "new-delhi",
    originName: "Delhi",
    originState: "Delhi",
    destSlug: "kanpur",
    destName: "Kanpur",
    destState: "Uttar Pradesh",
    distanceKm: 495,
    transitHours: 8.5,
    highway: "Yamuna & Agra-Lucknow Expressway",
    estimatedTolls: 810,
    popularCargo: "FMCG, hardware, consumer electronics, retail inventory",
    returnLoadAvailable: true,
  },
  {
    slug: "kanpur-to-delhi",
    originSlug: "kanpur",
    originName: "Kanpur",
    originState: "Uttar Pradesh",
    destSlug: "new-delhi",
    destName: "Delhi",
    destState: "Delhi",
    distanceKm: 495,
    transitHours: 8.5,
    highway: "Agra-Lucknow & Yamuna Expressway",
    estimatedTolls: 810,
    popularCargo: "Leather goods, industrial footwear, chemicals, plastics",
    returnLoadAvailable: true,
  },
  {
    slug: "mumbai-to-surat",
    originSlug: "mumbai",
    originName: "Mumbai",
    originState: "Maharashtra",
    destSlug: "surat",
    destName: "Surat",
    destState: "Gujarat",
    distanceKm: 285,
    transitHours: 6,
    highway: "NH-48",
    estimatedTolls: 460,
    popularCargo: "Port containers, FMCG, electronics, packaging material",
    returnLoadAvailable: true,
  },
  {
    slug: "surat-to-mumbai",
    originSlug: "surat",
    originName: "Surat",
    originState: "Gujarat",
    destSlug: "mumbai",
    destName: "Mumbai",
    destState: "Maharashtra",
    distanceKm: 285,
    transitHours: 6,
    highway: "NH-48",
    estimatedTolls: 460,
    popularCargo: "Textiles, synthetic fabrics, diamonds, chemical goods",
    returnLoadAvailable: true,
  },
  {
    slug: "chennai-to-hyderabad",
    originSlug: "chennai",
    originName: "Chennai",
    originState: "Tamil Nadu",
    destSlug: "hyderabad",
    destName: "Hyderabad",
    destState: "Telangana",
    distanceKm: 630,
    transitHours: 11,
    highway: "NH-16 / NH-65",
    estimatedTolls: 980,
    popularCargo: "Automotive components, port cargo, electronics, hardware",
    returnLoadAvailable: true,
  },
  {
    slug: "hyderabad-to-chennai",
    originSlug: "hyderabad",
    originName: "Hyderabad",
    originState: "Telangana",
    destSlug: "chennai",
    destName: "Chennai",
    destState: "Tamil Nadu",
    distanceKm: 630,
    transitHours: 11,
    highway: "NH-65 / NH-16",
    estimatedTolls: 980,
    popularCargo: "Bulk pharmaceuticals, agricultural produce, seeds, poultry",
    returnLoadAvailable: true,
  },
  {
    slug: "bengaluru-to-kochi",
    originSlug: "bengaluru",
    originName: "Bengaluru",
    originState: "Karnataka",
    destSlug: "kochi",
    destName: "Kochi",
    destState: "Kerala",
    distanceKm: 540,
    transitHours: 10,
    highway: "NH-544 / NH-44",
    estimatedTolls: 860,
    popularCargo: "Consumer electronics, retail goods, hardware, industrial spares",
    returnLoadAvailable: true,
  },
  {
    slug: "kochi-to-bengaluru",
    originSlug: "kochi",
    originName: "Kochi",
    originState: "Kerala",
    destSlug: "bengaluru",
    destName: "Bengaluru",
    destState: "Karnataka",
    distanceKm: 540,
    transitHours: 10,
    highway: "NH-544 / NH-44",
    estimatedTolls: 860,
    popularCargo: "Spices, coir products, sea container imports, rubber goods",
    returnLoadAvailable: true,
  },
  {
    slug: "kolkata-to-asansol",
    originSlug: "kolkata",
    originName: "Kolkata",
    originState: "West Bengal",
    destSlug: "asansol",
    destName: "Asansol",
    destState: "West Bengal",
    distanceKm: 215,
    transitHours: 4.5,
    highway: "NH-19 (GT Road)",
    estimatedTolls: 320,
    popularCargo: "FMCG, hardware, wholesale electronics, retail inventory",
    returnLoadAvailable: true,
  },
  {
    slug: "asansol-to-kolkata",
    originSlug: "asansol",
    originName: "Asansol",
    originState: "West Bengal",
    destSlug: "kolkata",
    destName: "Kolkata",
    destState: "West Bengal",
    distanceKm: 215,
    transitHours: 4.5,
    highway: "NH-19 (GT Road)",
    estimatedTolls: 320,
    popularCargo: "Steel sheets, industrial fabrication, coal derivatives",
    returnLoadAvailable: true,
  },
  {
    slug: "kolkata-to-durgapur",
    originSlug: "kolkata",
    originName: "Kolkata",
    originState: "West Bengal",
    destSlug: "durgapur",
    destName: "Durgapur",
    destState: "West Bengal",
    distanceKm: 175,
    transitHours: 3.5,
    highway: "NH-19",
    estimatedTolls: 260,
    popularCargo: "Commercial consumer goods, chemicals, packaging, spares",
    returnLoadAvailable: true,
  },
  {
    slug: "durgapur-to-kolkata",
    originSlug: "durgapur",
    originName: "Durgapur",
    originState: "West Bengal",
    destSlug: "kolkata",
    destName: "Kolkata",
    destState: "West Bengal",
    distanceKm: 175,
    transitHours: 3.5,
    highway: "NH-19",
    estimatedTolls: 260,
    popularCargo: "Alloy steel, industrial castings, engineering components",
    returnLoadAvailable: true,
  },
  {
    slug: "delhi-to-agra",
    originSlug: "new-delhi",
    originName: "Delhi",
    originState: "Delhi",
    destSlug: "agra",
    destName: "Agra",
    destState: "Uttar Pradesh",
    distanceKm: 230,
    transitHours: 4,
    highway: "Yamuna Expressway",
    estimatedTolls: 415,
    popularCargo: "Consumer retail, e-commerce packages, electronics, pharmaceuticals",
    returnLoadAvailable: true,
  },
  {
    slug: "agra-to-delhi",
    originSlug: "agra",
    originName: "Agra",
    originState: "Uttar Pradesh",
    destSlug: "new-delhi",
    destName: "Delhi",
    destState: "Delhi",
    distanceKm: 230,
    transitHours: 4,
    highway: "Yamuna Expressway",
    estimatedTolls: 415,
    popularCargo: "Leather footwear, handicrafts, marble stone work, confectionery",
    returnLoadAvailable: true,
  },
  {
    slug: "pune-to-hyderabad",
    originSlug: "pune",
    originName: "Pune",
    originState: "Maharashtra",
    destSlug: "hyderabad",
    destName: "Hyderabad",
    destState: "Telangana",
    distanceKm: 560,
    transitHours: 10,
    highway: "NH-65",
    estimatedTolls: 840,
    popularCargo: "Auto parts, engineering equipment, IT supplies, pharmaceuticals",
    returnLoadAvailable: true,
  },
  {
    slug: "hyderabad-to-pune",
    originSlug: "hyderabad",
    originName: "Hyderabad",
    originState: "Telangana",
    destSlug: "pune",
    destName: "Pune",
    destState: "Maharashtra",
    distanceKm: 560,
    transitHours: 10,
    highway: "NH-65",
    estimatedTolls: 840,
    popularCargo: "Pharma formulations, poultry feed, electronic assemblies",
    returnLoadAvailable: true,
  },
];

/**
 * Retrieve a corridor by its origin-to-destination slug.
 * Fallback: parses "{origin}-to-{destination}" dynamically if not explicitly in popular list.
 */
export function getCorridorBySlug(slug) {
  if (!slug) return null;
  const clean = String(slug).toLowerCase().trim();

  const found = POPULAR_CORRIDORS.find(c => c.slug === clean);
  if (found) return found;

  // Dynamic parser for any "{origin}-to-{destination}" format
  if (clean.includes("-to-")) {
    const [orig, dest] = clean.split("-to-");
    const origName = orig.replace(/-/g, " ").replace(/\b\w/g, l => l.toUpperCase());
    const destName = dest.replace(/-/g, " ").replace(/\b\w/g, l => l.toUpperCase());
    
    // Estimate distance baseline: 450 km default
    return {
      slug: clean,
      originSlug: orig,
      originName: origName,
      originState: "India",
      destSlug: dest,
      destName: destName,
      destState: "India",
      distanceKm: 450,
      transitHours: 10,
      highway: "National Highway Trunk Corridor",
      estimatedTolls: 700,
      popularCargo: "Industrial goods, commercial freight, FMCG, retail inventory",
      returnLoadAvailable: true,
      isDynamicallyComputed: true,
    };
  }

  return null;
}
